### PR TITLE
EB-Initial-Commit-boilerplate-html

### PR DESCRIPTION
**Pull request by ericberringer**
Added boilerplate html to scotland.html

```
git fetch --all
git checkout EB-Scotland
```

### CODE REVIEW

**Review by SLLittrell — APPROVED** [review]
blah blah yes

**Review by AndreaMays — APPROVED** [review]
Cool

**Comment by ericberringer** [comment]
Look at the Second Commit. I am a ding dong and did it wrong.

**Review by jashah46 — COMMENTED** [review]
Things look good! Great job and thanks for the groundwork. I'd be happy to approve but I'm a lil afraid of merging anything at this point.

**Review by SLLittrell — APPROVED** [review]
looks good!

**Pull request merged**
