### PR TITLE
Drea final edits

### PR DESCRIPTION
**Pull request by AndreaMays**
Hey Guys,

Here is my final edit of my page. You should see: the header is black, the flag on the right, Netherlands writing in red at top, black banner, a big downtown pic of Amsterdam, small pics in each category, blue squares, and dark writing in each square.

Please let me know if you find anything that needs changes.

```
git fetch all
git checkout am-netherlands-citypic
serve
```

### CODE REVIEW

**Review by SLLittrell — DISMISSED** [review]
looks good!! great job!!

**Review by SLLittrell — COMMENTED** [review]
hey there is a conflict in your index.html file having to do with the links. resolve and push up another commit before we merge! thanks

**Review by SLLittrell — APPROVED** [review]
yay!!!

**Comment by AndreaMays** [comment]
Moving on

**Pull request closed without merging**
